import type { Metadata } from "next";
import "./globals.css";
import AOSWrapper from "@/lib/AOSWrapper";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Destrezzza Art House",
  description: "Generated by create next app",
  icons: {
    icon: "/Icon.png", 
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={inter.className} >
        <AOSWrapper >
        {children}
        </AOSWrapper>
      </body>
    </html>
  );
}
