import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import GlobalLoader from "@/components/utils/GlobalLoader";

const inter = Inter({ subsets: ["latin"], display: 'swap' });

export const metadata: Metadata = {
  title: "Destrezzza Art House",
  description: "Generated by create next app",
  icons: {
    icon: "/Icon.png", 
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalLoader />
        {children}
      </body>
    </html>
  );
}
